PERMISSIONS = [
    {
        "code": "home.view",
        "name": "查看首页",
        "type": "page",
        "route": "/",
        "children": [
            ("home.dashboard.view", "查看首页看板数据", "api", None, "GET", "/api/dashboard"),
            ("home.data.refresh", "刷新首页数据", "button", None, None, None),
            ("home.data.sync", "同步新数据", "button", None, "POST", "/api/refresh/trigger"),
        ],
    },
    {
        "code": "follow.view",
        "name": "查看线索运营监控",
        "type": "page",
        "route": "/follow-up",
        "children": [
            ("follow.task.create", "创建治理任务", "api", None, "POST", "/api/governance/tasks"),
            ("follow.task.edit", "编辑治理任务门店", "api", None, "PUT", "/api/governance/tasks/<task_id>/stores"),
            ("follow.task.status", "流转治理任务状态", "api", None, "PATCH", "/api/governance/tasks/<task_id>/status"),
            ("follow.task.status", "删除治理任务", "api", None, "DELETE", "/api/governance/tasks/<task_id>"),
            ("follow.record.edit", "编辑门店跟进记录", "api", None, "POST", "/api/governance/tasks/<task_id>/follow-records"),
            ("follow.reason.config.manage", "管理跟进原因配置", "api", None, "POST", "/api/governance/follow-reasons"),
            ("follow.summary.generate", "生成治理总结", "api", None, "POST", "/api/governance/tasks/<task_id>/summary/generate"),
            ("follow.summary.confirm", "确认治理总结", "api", None, "POST", "/api/governance/tasks/<task_id>/summary"),
            ("follow.distribution.entry", "查看跟进次数分布入口", "button", None, None, None),
            ("follow.data.refresh", "刷新线索运营监控数据", "button", None, None, None),
        ],
    },
    {
        "code": "follow.distribution.view",
        "name": "查看跟进次数分布",
        "type": "page",
        "route": "/follow-up/distribution",
        "children": [
            ("follow.distribution.query", "查询跟进次数分布", "api", None, "GET", "/api/follow-up/distribution"),
            ("follow.distribution.search", "搜索跟进门店", "button", None, None, None),
            ("follow.distribution.export", "导出跟进次数分布", "button", None, None, None),
        ],
    },
    {
        "code": "operations.view",
        "name": "查看运营数据",
        "type": "page",
        "route": "/operations-data",
        "children": [
            ("operations.customer_visit.entry", "查看客流明细入口", "button", None, None, None),
            ("operations.visit_stats.entry", "查看客流统计入口", "button", None, None, None),
            ("operations.outbound_call_detail.entry", "查看外呼明细入口", "button", None, None, None),
            ("operations.outbound_call_stats.entry", "查看外呼统计入口", "button", None, None, None),
        ],
    },
    {
        "code": "outbound_call_detail.view",
        "name": "查看外呼明细",
        "type": "page",
        "route": "/outbound-call-detail",
        "children": [
            ("outbound_call_detail.summary", "查看外呼明细卡片", "api", None, "GET", "/api/outbound-call/summary"),
            ("outbound_call_detail.query", "查询外呼明细", "api", None, "GET", "/api/outbound-call/detail"),
            ("outbound_call_detail.options", "查询外呼日期范围", "api", None, "GET", "/api/outbound-call/options"),
            ("outbound_call_detail.filter", "使用外呼明细筛选", "button", None, None, None),
            ("outbound_call_detail.export", "导出外呼明细", "api", None, "GET", "/api/outbound-call/export"),
        ],
    },
    {
        "code": "outbound_call_stats.view",
        "name": "查看外呼统计",
        "type": "page",
        "route": "/outbound-call-stats",
        "children": [
            ("outbound_call_stats.options", "查询外呼统计筛选项", "api", None, "GET", "/api/outbound-call-stats/options"),
            ("outbound_call_stats.summary", "查看外呼统计总览", "api", None, "GET", "/api/outbound-call-stats/summary"),
            ("outbound_call_stats.trend", "查看外呼趋势", "api", None, "GET", "/api/outbound-call-stats/trend"),
            ("outbound_call_stats.stores", "查看门店外呼统计", "api", None, "GET", "/api/outbound-call-stats/stores"),
            ("outbound_call_stats.consultants", "查看顾问外呼统计", "api", None, "GET", "/api/outbound-call-stats/consultants"),
            ("outbound_call_stats.numbers", "查看号码触达统计", "api", None, "GET", "/api/outbound-call-stats/numbers"),
            ("outbound_call_stats.quality", "查看外呼质量异常", "api", None, "GET", "/api/outbound-call-stats/quality"),
            ("outbound_call_stats.filter", "使用外呼统计筛选", "button", None, None, None),
            ("outbound_call_stats.drilldown", "下钻外呼明细", "button", None, None, None),
            ("outbound_call_stats.export", "导出外呼统计", "api", None, "GET", "/api/outbound-call-stats/export"),
        ],
    },
    {
        "code": "customer_visit.view",
        "name": "查看客流明细",
        "type": "page",
        "route": "/customer-visit",
        "children": [
            ("customer_visit.stats.view", "查看客流明细统计", "api", None, "GET", "/api/customer_visit/stats"),
            ("customer_visit.query", "查询客流明细", "api", None, "GET", "/api/customer_visit/detail"),
            ("customer_visit.filter", "使用客流明细筛选", "button", None, None, None),
            ("customer_visit.export", "导出客流明细", "api", None, "GET", "/api/customer_visit/export"),
        ],
    },
    {
        "code": "visit_stats.view",
        "name": "查看客流统计",
        "type": "page",
        "route": "/visit-stats",
        "children": [
            ("visit_stats.query", "查询客流统计", "api", None, "GET", "/api/visit_stats"),
            ("visit_stats.filter", "使用客流统计筛选", "button", None, None, None),
            ("visit_stats.drilldown", "下钻客流明细", "button", None, None, None),
            ("visit_stats.export", "导出客流统计", "api", None, "GET", "/api/visit_stats/export"),
        ],
    },
    {
        "code": "data_query.view",
        "name": "查看数据查询",
        "type": "page",
        "route": "/data-query",
        "children": [
            ("data_query.tables.view", "查看可查询数据表", "api", None, "GET", "/api/query/tables"),
            ("data_query.schema.view", "查看表结构", "api", None, "GET", "/api/query/table/<table_name>/schema"),
            ("data_query.detail.execute", "执行明细查询", "api", None, "POST", "/api/query/detail"),
            ("data_query.aggregate.execute", "执行聚合查询", "api", None, "POST", "/api/query/aggregate"),
            ("data_query.advanced_filter", "使用高级筛选", "button", None, None, None),
            ("data_query.history.view", "查看查询历史", "page", None, None, None),
            ("data_query.export", "导出查询结果", "api", None, "POST", "/api/query/export"),
        ],
    },
    {
        "code": "dealer_management.view",
        "name": "查看经销商管理",
        "type": "page",
        "route": "/dealer-management",
        "children": [
            ("dealer_daily_report.entry", "查看运营日报入口", "button", None, None, None),
            ("dealer_overdue_query.entry", "查看逾期查询入口", "button", None, None, None),
            ("store_profile.entry", "查看门店档案入口", "button", None, None, None),
            ("store_management.entry", "查看门店管理入口", "button", None, None, None),
        ],
    },
    {
        "code": "store_profile.view",
        "name": "查看门店档案",
        "type": "page",
        "route": "/store_profile",
        "children": [
            ("store_profile.query", "查询门店档案", "api", None, "GET", "/api/store-profile/stores"),
            ("store_profile.summary", "查看门店档案汇总", "api", None, "GET", "/api/store-profile/summary"),
            ("store_profile.filters", "查询门店档案筛选项", "api", None, "GET", "/api/store-profile/filters"),
            ("store_profile.frequent.view", "查看高频问题门店", "api", None, "GET", "/api/store-profile/frequent-stores"),
            ("store_profile.reason_analysis.view", "查看跟进原因分析", "api", None, "GET", "/api/store-profile/reason-analysis"),
            ("store_profile.detail.view", "查看门店详情", "page", "/store_detail/<store_code>", "GET", "/api/store-profile/<store_code>/basic-info"),
        ],
    },
    {
        "code": "store_management.view",
        "name": "查看门店管理",
        "type": "page",
        "route": "/store_management",
        "children": [
            ("store_management.query", "查询门店管理列表", "api", None, "GET", "/api/store-management/stores"),
            ("store_management.edit", "编辑门店治理信息", "api", None, "PATCH", "/api/store-management/stores/<store_code>"),
            ("store_management.config.view", "查看治理状态和评级配置", "api", None, "GET", "/api/store-management/statuses"),
            ("store_management.config.manage", "管理治理状态和评级配置", "api", None, "POST", "/api/store-management/statuses"),
        ],
    },
    {
        "code": "dealer_overdue_query.view",
        "name": "查看逾期查询",
        "type": "page",
        "route": "/dealer-management/overdue-query",
        "children": [
            ("dealer_overdue_query.query", "查询逾期数据", "api", None, "GET", "/api/dealer-management/overdue-query"),
            ("dealer_overdue_query.export", "导出逾期数据", "api", None, "GET", "/api/dealer-management/overdue-query/export"),
        ],
    },
    {
        "code": "dealer_daily_report.view",
        "name": "查看运营日报",
        "type": "page",
        "route": "/dealer-management/daily-report",
        "children": [
            ("dealer_daily_report.query", "查询运营日报", "api", None, "GET", "/api/dealer-daily-report"),
            ("dealer_daily_report.filter", "使用运营日报筛选", "button", None, None, None),
            ("dealer_daily_report.sort", "运营日报排序", "button", None, None, None),
            ("dealer_daily_report.export", "导出运营日报", "api", None, "GET", "/api/dealer-daily-report/export"),
            ("dealer_daily_report.export_template", "导出日报模板", "api", None, "GET", "/api/dealer-daily-report/export-template"),
            ("dealer_daily_report.export_custom_range", "导出自定义周期日报", "api", None, "GET", "/api/dealer-daily-report/export-custom-range"),
        ],
    },
    {
        "code": "key_store_wind.view",
        "name": "查看重点店风向监测",
        "type": "page",
        "route": "/key-store-wind",
        "children": [
            ("key_store_wind.metric_window.switch", "切换观察窗口", "button", None, None, None),
            ("key_store_wind.trend.view", "查看趋势镜面", "page", None, None, None),
            ("key_store_wind.absolute.view", "查看绝对值镜面", "page", None, None, None),
            ("key_store_wind.store_detail.view", "查看重点店明细", "button", None, None, None),
            ("key_store_wind.sort", "重点店明细排序", "button", None, None, None),
        ],
    },
    {
        "code": "funnel_target.view",
        "name": "查看线上线索漏斗目标达成",
        "type": "page",
        "route": "/funnel-target-analysis",
        "children": [
            ("funnel_target.home_card", "查看首页漏斗目标模块", "api", None, "GET", "/api/funnel-target/home-summary"),
            ("funnel_target.overview", "查看漏斗目标总览", "api", None, "GET", "/api/funnel-target/overview"),
            ("funnel_target.dashboard_summary", "查看漏斗驾驶舱摘要", "api", None, "GET", "/api/funnel-target/dashboard-summary"),
            ("funnel_target.dashboard_regions", "查看漏斗驾驶舱区域汇总", "api", None, "GET", "/api/funnel-target/dashboard-regions"),
            ("funnel_target.query_dealer_models", "查询门店车型漏斗", "api", None, "GET", "/api/funnel-target/dealer-models"),
            ("funnel_target.query_org_dealers", "查询组织门店漏斗", "api", None, "GET", "/api/funnel-target/org-dealers"),
            ("funnel_target.query_channels", "查询车型渠道漏斗", "api", None, "GET", "/api/funnel-target/channels"),
            ("funnel_target.filter", "使用漏斗目标筛选", "api", None, "GET", "/api/funnel-target/filter-options"),
            ("funnel_target.config.view", "查看漏斗目标配置", "api", None, "GET", "/api/funnel-target/config/visit-targets"),
            ("funnel_target.config.manage", "管理漏斗目标配置", "api", None, "POST", "/api/funnel-target/config/visit-targets"),
            ("funnel_target.sales_target.import", "导入成交目标", "api", None, "POST", "/api/funnel-target/config/sales-targets/import"),
            ("funnel_target.recompute", "重算漏斗目标", "api", None, "POST", "/api/funnel-target/recompute"),
            ("funnel_target.export", "导出漏斗目标数据", "button", None, None, None),
        ],
    },
    {
        "code": "admin.module",
        "name": "账号权限",
        "type": "module",
        "route": "/admin",
        "children": [
            ("admin.users.view", "查看账号管理", "page", "/admin/users", "GET", "/api/admin/users"),
            ("admin.users.create", "新建账号", "api", None, "POST", "/api/admin/users"),
            ("admin.users.edit", "编辑账号", "api", None, "PUT", "/api/admin/users/<id>"),
            ("admin.users.status", "启停账号", "api", None, "PATCH", "/api/admin/users/<id>/status"),
            ("admin.users.reset_password", "重置密码", "api", None, "POST", "/api/admin/users/<id>/reset-password"),
            ("admin.roles.view", "查看角色管理", "page", "/admin/roles", "GET", "/api/admin/roles"),
            ("admin.roles.create", "新建角色", "api", None, "POST", "/api/admin/roles"),
            ("admin.roles.edit", "编辑角色", "api", None, "PUT", "/api/admin/roles/<id>"),
            ("admin.roles.delete", "删除角色", "api", None, "DELETE", "/api/admin/roles/<id>"),
            ("admin.roles.permissions.edit", "配置角色权限", "api", None, "PUT", "/api/admin/roles/<id>/permissions"),
            ("admin.data_scope.edit", "配置数据范围", "button", None, None, None),
            ("admin.audit_logs.view", "查看操作日志", "page", "/admin/audit-logs", "GET", "/api/admin/audit-logs"),
            ("admin.login_logs.view", "查看登录日志", "page", "/admin/login-logs", "GET", "/api/admin/login-logs"),
        ],
    },
]


OPERATIONS_EXTRA_API_PERMISSIONS = [
    ("data_query.schema.view", "GET", "/api/query/filterable/<table_name>"),
    ("data_query.schema.view", "GET", "/api/query/groupable/<table_name>"),
    ("data_query.schema.view", "GET", "/api/query/aggregatable/<table_name>"),
    ("funnel_target.config.view", "GET", "/api/funnel-target/config/conversion-rates"),
    ("funnel_target.config.view", "GET", "/api/funnel-target/config/sales-targets"),
    ("funnel_target.config.view", "GET", "/api/funnel-target/config/model-source-values"),
    ("funnel_target.config.view", "GET", "/api/funnel-target/config/model-mappings"),
    ("funnel_target.view", "GET", "/api/funnel-target/dashboard-summary"),
    ("funnel_target.view", "GET", "/api/funnel-target/dashboard-regions"),
    ("funnel_target.config.manage", "POST", "/api/funnel-target/config/conversion-rates"),
    ("funnel_target.config.manage", "POST", "/api/funnel-target/config/model-source-values/scan"),
    ("funnel_target.config.manage", "POST", "/api/funnel-target/config/model-mappings"),
    ("store_profile.query", "GET", "/api/store-profile/search"),
    ("store_profile.detail.view", "GET", "/api/store-profile/<store_code>/daily-stats"),
    ("store_profile.detail.view", "GET", "/api/store-profile/<store_code>/follow-history"),
    ("store_profile.detail.view", "GET", "/api/store-profile/<store_code>/reason-analysis"),
    ("store_management.query", "GET", "/api/store-management/filters"),
    ("store_management.config.manage", "PATCH", "/api/store-management/statuses/<id>"),
    ("store_management.config.manage", "DELETE", "/api/store-management/statuses/<id>"),
    ("dealer_daily_report.query", "GET", "/api/store-portfolio-monitor/stores"),
    ("dealer_daily_report.query", "GET", "/api/store-portfolio-monitor/daily-series"),
    ("follow.view", "GET", "/api/governance/tasks"),
    ("follow.view", "GET", "/api/governance/tasks/<task_id>"),
    ("follow.view", "GET", "/api/governance/tasks/<task_id>/summary"),
    ("follow.view", "GET", "/api/governance/follow-reasons"),
    ("follow.view", "POST", "/api/governance/filter-preview"),
    ("follow.task.status", "DELETE", "/api/governance/tasks/<task_id>"),
    ("follow.reason.config.manage", "PATCH", "/api/governance/follow-reasons/<id>"),
    ("follow.reason.config.manage", "DELETE", "/api/governance/follow-reasons/<id>"),
]
